services:
  booktest:
    image: app
    build:
      context: .
      dockerfile: ./View/Dockerfile
    environment:
      ASPNETCORE_HTTP_PORTS: 5000
    ports:
      - "5000:5000"
      - "5001:5001"
  app.database:
    image: postgres:latest
    container_name: App.database
    environment:
      POSTGRES_DB: Books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432