# This is a generated file. Not intended for manual editing.
services:
  booktest:
    build:
      context: "/home/tf/Музыка/test work for vacansy/BookTest"
      dockerfile: "./View/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/View.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/View.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "app:dev"
    ports: []
    volumes:
    - "/home/tf/.nuget/packages:/home/app/.nuget/packages"
    - "/home/tf/Музыка/test work for vacansy/BookTest/View:/app:rw"
    - "/home/tf/Музыка/test work for vacansy/BookTest:/src:rw"
    working_dir: "/app"
